# Generated by Django 3.0.5 on 2023-01-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
