# Generated by Django 3.0.5 on 2023-02-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_userlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireapi',
            old_name='isActive',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='questionnaireapi',
            name='number_of_questions',
            field=models.IntegerField(default=2),
        ),
    ]
