# Generated by Django 3.0.5 on 2023-02-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20230201_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireapi',
            old_name='isActive',
            new_name='status',
        ),
    ]
