# Generated by Django 3.0.5 on 2023-02-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20230202_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireapi',
            name='status',
            field=models.CharField(max_length=45),
        ),
    ]
