# Generated by Django 3.0.5 on 2023-02-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20230202_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireapi',
            name='status',
        ),
        migrations.AddField(
            model_name='questionnaireapi',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
