# Generated by Django 3.0.5 on 2023-02-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20230202_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireapi',
            old_name='isActive',
            new_name='is_Active',
        ),
    ]
