# Generated by Django 3.0.5 on 2023-02-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20230202_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Designation',
                'ordering': ['updated'],
            },
        ),
        migrations.DeleteModel(
            name='Designations',
        ),
    ]
