# Generated by Django 3.0.5 on 2023-02-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20230202_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPResponseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=120)),
                ('Answer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Response',
            },
        ),
    ]
