# Generated by Django 3.0.5 on 2023-02-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_kpresponsereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpresponsereport',
            old_name='Question',
            new_name='field2',
        ),
    ]
