# Generated by Django 3.0.5 on 2023-02-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20230208_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KPResponseReport',
            new_name='Responses',
        ),
    ]
