# Generated by Django 4.1.6 on 2023-02-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20230208_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='field2',
            new_name='Question',
        ),
    ]
