# Generated by Django 4.1.6 on 2023-02-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_rename_field2_responses_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireapi',
            name='number_of_questions',
            field=models.BigIntegerField(default=2),
        ),
    ]
