# Generated by Django 4.1.6 on 2023-02-14 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alter_questionnaireapi_number_of_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=750)),
                ('is_Active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_questions', models.BigIntegerField(default=2)),
                ('active_till', models.DateField(verbose_name=datetime.datetime.now)),
                ('target_app', models.CharField(max_length=45)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'QuestionnaireDb',
                'ordering': ['-updated'],
            },
        ),
    ]
